site_name: IFRS9Pro Docs
site_url: https://Cjyyaotse.github.io/ifrs9pro_backend/

theme:
  name: mkdocs
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: blue
    accent: light blue
nav:
  - Overview: index.md

  - Usage Guide:
      - Users and authentication: authentication.md
      - Dashboard: dashboard.md
      - Portfolios: portfolios.md
      - Feedback: feedback.md



